//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_1_3_Operators.Properties
{
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BTcy1DCE32820Ti6We5U5Q==")]
        public string PuzzleFarmerKey1 {
            get {
                return ((string)(this["PuzzleFarmerKey1"]));
            }
            set {
                this["PuzzleFarmerKey1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B4hXmFaDNUaCz7zDG3DUTA==")]
        public string PuzzleFarmerKey2 {
            get {
                return ((string)(this["PuzzleFarmerKey2"]));
            }
            set {
                this["PuzzleFarmerKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cag6XKil1HA=")]
        public string PuzzleFarmerMaxAttemptsCount {
            get {
                return ((string)(this["PuzzleFarmerMaxAttemptsCount"]));
            }
            set {
                this["PuzzleFarmerMaxAttemptsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select the operation:{1}{0}1 - Puzzle The farmer, wolf, goat and cabbage;{1}{0}2 " +
            "- Simple calculator;{1}{0}3 - Factorial;{1}{0}4 - Guess the number;{1}{0}q - Exi" +
            "t!!!{1}{2}")]
        public string MainMenu {
            get {
                return ((string)(this["MainMenu"]));
            }
            set {
                this["MainMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HGibqDVVnoc=")]
        public string MainMenu_MaxIncorectInputCount {
            get {
                return ((string)(this["MainMenu_MaxIncorectInputCount"]));
            }
            set {
                this["MainMenu_MaxIncorectInputCount"] = value;
            }
        }
    }
}
