//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_1_5_Strings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select the operation:{1}{0}1 - Absolute value of the difference between two numbe" +
            "rs;{1}{0}2 - Record of the number as a binary string;{1}{0}3 - Morse code as a s" +
            "ound;{1}{0}q - Exit!!!{1}{2}")]
        public string MainMenu {
            get {
                return ((string)(this["MainMenu"]));
            }
            set {
                this["MainMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("s/upcHu4QNo=")]
        public string AbsoluteValue_MinTypingValue {
            get {
                return ((string)(this["AbsoluteValue_MinTypingValue"]));
            }
            set {
                this["AbsoluteValue_MinTypingValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P00cYl/aeOs=")]
        public string AbsoluteValue_MaxTypingValue {
            get {
                return ((string)(this["AbsoluteValue_MaxTypingValue"]));
            }
            set {
                this["AbsoluteValue_MaxTypingValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PVniIRKwu3k=\r\n")]
        public string AbsoluteValue_Delimiter {
            get {
                return ((string)(this["AbsoluteValue_Delimiter"]));
            }
            set {
                this["AbsoluteValue_Delimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("s/upcHu4QNo=")]
        public string AbsoluteValue_ReplaceToSymbol {
            get {
                return ((string)(this["AbsoluteValue_ReplaceToSymbol"]));
            }
            set {
                this["AbsoluteValue_ReplaceToSymbol"] = value;
            }
        }
    }
}
